### ISSUE TITLE
qs.reports.html(stock, "SPX") report index error

### ISSUE THREAD

**Issue by jackieli19** [ranaroussi/quantstats#61]
I try to test the output function. My code is as below:

`
import quantstats as qs

qs.extend_pandas()

stock = qs.utils.download_returns('FB')

qs.reports.html(stock, "SPY")
`

I think this is the most simple case and should work. But I get the following error:
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by kartiksubbarao** [comment]
I ran into the same error with 0.26 (I'm running pandas 1.2.1 and numpy 1.19.5). In my case, I tracked it down to an issue with the `yearly_returns()` function in `_plotting/wrappers.py`. In 0.26, it calls `_utils.group_returns()` to aggregate returns for each year. The problem is that the resulting object has index values with just the year (e.g. '2019' instead of the full date '2019-12-31'). This leads to a mismatch between the returns index and the benchmarks index (which does have the full date), eventually leading to the IndexError.

As a workaround, I reverted that portion of code back to the 0.25 version and it now works fine.

I replaced this: https://github.com/ranaroussi/quantstats/blob/master/quantstats/_plotting/wrappers.py#L362-L365

With this: https://github.com/ranaroussi/quantstats/blob/bf3cc8bfdf75f6a5adfe7ae88a0f84734b70d9fb/quantstats/_plotting/wrappers.py#L353-L358

**Comment by AnasEssahal** [comment]
Hi, 
I am still having the issue "IndexError: index 0 is out of bounds for axis 0 with size 0"
I have just installed the module so i have exactly the same code you are showing above.
I am using Conda ( installed today as well)
QuantStats-0.0.26
yfinance-0.1.55
